=== CJStandingwater/cookbook/schema/recipe.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Recipe",
  "type": "object",

  "required": [
    "id",
    "title",
    "authors",
    "ingredients",
    "instructions"
  ],

  "properties": {
    "id": {
      "type": "string",
      "minLength": 36,
      "maxLength": 36,
      "pattern": "^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-4[0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
    },

    "title": {
      "type": "string",
      "minLength": 1
    },

    "authors": {
      "type": "array",
      "minItems": 1,
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },

    "image": {
      "$ref": "common.json#/$defs/image"
    },

    "ingredients": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "items"
        ],
        "properties": {
          "section": {
            "type": "string",
            "minLength": 1
          },

          "items": {
            "type": "array",
            "minItems": 1,
            "items": {
              "$ref": "common.json#/$defs/ingredient"
            }
          }
        },
        "additionalProperties": false
      }
    },

    "instructions": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "action",
          "content"
        ],
        "properties": {
          "action": {
            "type": "string",
            "$ref": "actions.enum.json"
          },

          "content": {
            "type": "string",
            "minLength": 1
          },

          "image": {
            "$ref": "common.json#/$defs/image"
          },

          "notes": {
            "type": "array",
            "minItems": 1,
            "items": {
              "type": "string",
              "minLength": 1
            }
          }
        },
        "additionalProperties": false
      }
    },

    "timings": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "object",
        "required": [
          "title",
          "minutes"
        ],
        "properties": {
          "title": {
            "type": "string",
            "minLength": 1
          },

          "minutes": {
            "type": "number",
            "exclusiveMinimum": 0
          }
        },
        "additionalProperties": false
      }
    },

    "servings": {
      "type": "number",
      "exclusiveMinimum": 0
    },

    "tags": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "$ref": "tags.flattened.json"
      }
    },

    "notes": {
      "type": "array",
      "minItems": 1,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },

    "nutrition": {
      "type": "object",
      "properties": {
        "calories": {
          "type": "number",
          "minimum": 0
        },
        "protein": {
          "type": "number",
          "minimum": 0
        },
        "fat": {
          "type": "number",
          "minimum": 0
        },
        "carbohydrates": {
          "type": "number",
          "minimum": 0
        },
        "fiber": {
          "type": "number",
          "minimum": 0
        }
      },
      "additionalProperties": false
    },

    "source": {
      "type": "string",
      "minLength": 1
    },

    "tools": {
      "type": "array",
      "uniqueItems": true,
      "items": {
        "type": "string",
        "minLength": 1
      }
    },

    "difficulty": {
      "type": "string",
      "$ref": "difficulty.enum.json"
    }
  },

  "additionalProperties": false
}

=== CJStandingwater/cookbook/recipes/3dd38c44-02d5-4e07-be7a-d73fb621940a.json
{
  "id": "3dd38c44-02d5-4e07-be7a-d73fb621940a",
  "title": "Simple Carrot Cake",
  "authors": [
    "LouAnn Jensen"
  ],
  "ingredients": [
    {
      "section": "Cake",
      "items": [
        {
          "ingredient": "Flour",
          "volume_ml": 354.882
        },
        {
          "ingredient": "Sugar",
          "volume_ml": 295.735
        },
        {
          "ingredient": "Baking Soda",
          "volume_ml": 7.393
        },
        {
          "ingredient": "Cinnamon",
          "volume_ml": 7.393
        },
        {
          "ingredient": "Salt",
          "volume_ml": 1.232
        },
        {
          "ingredient": "Carrot",
          "form": [
            "pureed"
          ],
          "weight_g": 255.146,
          "note": "The original recipe called for two 4.5 oz jars of strained carrots (9 oz total). The modern equivalent is jarred baby food carrot puree, which is now commonly sold in 4 oz jars. You will need 9 oz total, so buy three 4 oz jars and weigh out the correct amount, or make your own fresh carrot puree."
        },
        {
          "ingredient": "Vegetable Oil",
          "volume_ml": 156.148,
          "note": "The original recipe did not specify the oil used. It is assumed any neutral cooking oil will work."
        },
        {
          "ingredient": "Egg",
          "count": 2
        },
        {
          "ingredient": "Vanilla Extract",
          "volume_ml": 1.232
        },
        {
          "ingredient": "Pineapple",
          "form": [
            "crushed",
            "drained"
          ],
          "weight_g": 226.796
        },
        {
          "ingredient": "Coconut",
          "form": [
            "shredded"
          ],
          "volume_ml": 156.148,
          "optional": true
        },
        {
          "ingredient": "Nuts",
          "form": [
            "chopped"
          ],
          "volume_ml": 118.294,
          "optional": true,
          "note": "The original recipe did not specify what type of nut, but walnuts or pecans will work best."
        }
      ]
    },
    {
      "section": "Cream Cheese Frosting",
      "items": [
        {
          "ingredient": "Cream Cheese",
          "weight_g": 85.049
        },
        {
          "ingredient": "Margarine",
          "volume_ml": 59.147,
          "substitutes": [
            [
              {
                "ingredient": "Butter",
                "volume_ml": 59.147
              }
            ]
          ]
        },
        {
          "ingredient": "Vanilla Extract",
          "volume_ml": 2.464
        },
        {
          "ingredient": "Powdered Sugar",
          "form": [
            "sifted"
          ],
          "volume_ml": 473.176
        }
      ]
    }
  ],
  "instructions": [
    {
      "action": "preheat",
      "content": "Preheat the oven to 350 degrees Fahrenheit."
    },
    {
      "action": "mix",
      "content": "In a medium mixing bowl, mix Flour, Sugar, Baking Soda, Cinnamon, and Salt."
    },
    {
      "action": "whisk",
      "content": "Whisk in Carrot Puree, Vegetable Oil, Eggs, and Vanilla Extract."
    },
    {
      "action": "fold",
      "content": "Fold in the Crushed Pineapple, and if using, the Shredded Coconut and Chopped Nuts."
    },
    {
      "action": "bake",
      "content": "Bake at 350 degrees Fahrenheit for 30-35 minutes."
    },
    {
      "action": "beat",
      "content": "In a small bowl, beat Cream Cheese, Margarine, Vanilla Extract, and Powdered Sugar until smooth."
    },
    {
      "action": "cool",
      "content": "When done, remove the cake from the oven and cool to room temperature.",
      "notes": [
        "Doneness can be checked by inserting a toothpick near the center of the cake. The cake is not done if wet batter sticks to the toothpick."
      ]
    },
    {
      "action": "chill",
      "content": "Once cooled to room temperature, chill in the refrigerator for 30-60 minutes.",
      "notes": [
        "Chilling before icing the cake can prevent tearing the cake."
      ]
    },
    {
      "action": "frost",
      "content": "Once chilled, frost the cake and serve.",
      "notes": [
        "It is recommended to divide the cake with three cuts along the long edge, and five along the short edge."
      ]
    }
  ],
  "timings": [
    {
      "title": "prep",
      "minutes": 15
    },
    {
      "title": "bake",
      "minutes": 35
    },
    {
      "title": "cool",
      "minutes": 120
    },
    {
      "title": "chill",
      "minutes": 60
    }
  ],
  "servings": 24,
  "tags": [
    "dessert",
    "fall",
    "comfort",
    "american",
    "cake"
  ],
  "source": "Pantry Potpourri",
  "tools": [
    "9x13 Pan",
    "Medium Mixing Bowl",
    "Small Mixing Bowl",
    "Whisk"
  ],
  "difficulty": "easy"
}

=== CJStandingwater/cookbook/recipes/4abfa8d1-1ef2-481a-b519-f872d662db73.json
{
  "id": "4abfa8d1-1ef2-481a-b519-f872d662db73",
  "title": "Slow Cooker Cheesy Potato Soup with Ham",
  "authors": [
    "fabeveryday"
  ],
  "ingredients": [
    {
      "items": [
        {
          "ingredient": "Hash Brown Potatoes",
          "weight_g": 794,
          "form": [
            "frozen",
            "thawed"
          ]
        },
        {
          "ingredient": "Ham",
          "volume_ml": 480,
          "weight_g": 230,
          "preferred_measurement": {
            "metric": "weight",
            "imperial": "volume"
          },
          "form": [
            "diced"
          ]
        },
        {
          "ingredient": "Onion",
          "volume_ml": 120,
          "weight_g": 130,
          "preferred_measurement": {
            "metric": "weight",
            "imperial": "volume"
          },
          "form": [
            "diced"
          ]
        },
        {
          "ingredient": "Celery Stalks",
          "count": 2,
          "form": [
            "chopped"
          ]
        },
        {
          "ingredient": "Chicken Broth",
          "volume_ml": 960
        },
        {
          "ingredient": "Salt",
          "volume_ml": 1.25,
          "weight_g": 1.5,
          "preferred_measurement": {
            "metric": "weight",
            "imperial": "volume"
          }
        },
        {
          "ingredient": "Pepper",
          "volume_ml": 1.25,
          "weight_g": 0.5,
          "preferred_measurement": {
            "metric": "weight",
            "imperial": "volume"
          }
        },
        {
          "ingredient": "Garlic Powder",
          "volume_ml": 1.25,
          "weight_g": 1,
          "preferred_measurement": {
            "metric": "weight",
            "imperial": "volume"
          },
          "substitutes": [
            [
              {
                "ingredient": "Garlic Clove",
                "count": 1,
                "form": [
                  "minced"
                ]
              }
            ]
          ]
        },
        {
          "ingredient": "Cream Cheese",
          "weight_g": 227,
          "form": [
            "softened"
          ]
        },
        {
          "ingredient": "Cheddar Cheese",
          "weight_g": 227,
          "form": [
            "shredded"
          ]
        },
        {
          "ingredient": "Green Onion",
          "volume_ml": 30,
          "weight_g": 20,
          "preferred_measurement": {
            "metric": "weight",
            "imperial": "volume"
          },
          "form": [
            "chopped"
          ],
          "note": "Or to taste; for garnish"
        }
      ]
    }
  ],
  "instructions": [
    {
      "action": "combine",
      "content": "Combine hash browns, ham, onion, celery, chicken broth, salt, pepper, and garlic powder in a slow cooker. Stir well and cover."
    },
    {
      "action": "simmer",
      "content": "Cook on Low until the celery is soft, 4 to 5 hours."
    },
    {
      "action": "stir",
      "content": "Mix in cream cheese and Cheddar cheese, stirring until melted. Cover and cook on Low for another 30 minutes, stirring occasionally."
    },
    {
      "action": "serve",
      "content": "Serve topped with chopped green onions."
    }
  ],
  "timings": [
    {
      "title": "prep time",
      "minutes": 5
    },
    {
      "title": "cook time",
      "minutes": 270
    },
    {
      "title": "total time",
      "minutes": 275
    }
  ],
  "servings": 6,
  "tags": [
    "dinner",
    "comfort",
    "slow-cook",
    "soup"
  ],
  "notes": [
    "A way to use leftover holiday ham."
  ],
  "nutrition": {
    "calories": 518,
    "protein": 24,
    "fat": 42,
    "carbohydrates": 28,
    "fiber": 2
  },
  "source": "https://www.allrecipes.com/recipe/273023/easy-slow-cooker-cheesy-potato-soup-with-ham/",
  "tools": [
    "Slow Cooker"
  ],
  "difficulty": "easy"
}

=== CJStandingwater/cookbook/recipes/61bff734-8f8e-4ccb-8e4b-47e33572ae8d.json
{
  "id": "61bff734-8f8e-4ccb-8e4b-47e33572ae8d",
  "title": "Classic Western Omelet",
  "authors": [
    "Admin"
  ],
  "ingredients": [
    {
      "section": "Filling",
      "items": [
        {
          "ingredient": "Unsalted Butter",
          "volume_ml": 29.574,
          "note": "Divided"
        },
        {
          "ingredient": "Red Bell Pepper",
          "form": [
            "diced"
          ],
          "volume_ml": 59.147
        },
        {
          "ingredient": "Green Bell Pepper",
          "form": [
            "diced"
          ],
          "volume_ml": 59.147
        },
        {
          "ingredient": "Yellow Onion",
          "form": [
            "diced"
          ],
          "volume_ml": 59.147
        },
        {
          "ingredient": "Scallion",
          "form": [
            "sliced"
          ],
          "count": 1,
          "note": "Thinly"
        },
        {
          "ingredient": "Deli Ham",
          "form": [
            "sliced",
            "chopped"
          ],
          "count": 2
        },
        {
          "ingredient": "Pepper Jack Cheese",
          "form": [
            "shredded"
          ],
          "volume_ml": 59.147
        }
      ]
    },
    {
      "section": "Egg Mix",
      "items": [
        {
          "ingredient": "Egg",
          "form": [
            "large"
          ],
          "count": 3
        },
        {
          "ingredient": "Salt",
          "volume_ml": 1.232
        }
      ]
    }
  ],
  "instructions": [
    {
      "action": "saute",
      "content": "Melt 1 tablespoon of the butter in a non-stick skillet over medium heat. Add the bell peppers and onions and saute until softened. Add the ham, scallion, and black pepper. Cook for 1-2 minutes and transfer the mixture. Clean the skillet."
    },
    {
      "action": "whisk",
      "content": "Whisk together the eggs and salt while the skillet reheats."
    },
    {
      "action": "assemble",
      "content": "Coat the skillet with the remaining 1 tablespoon of butter. Pour in the egg, and use a rubber spatula to gently tuck the edges of the egg inward. When the egg is half cooked, add the filling and cheese to half of the egg, and fold the empty half of the egg over the filling. Remove from heat and rest for 1 minute."
    },
    {
      "action": "serve",
      "content": "Serve the omelet immediately.",
      "notes": [
        "The omelet might cook better if covered with a lid before removing it from the heat.",
        "If making several omelets before serving, transfer them to a baking pan instead of allowing each omelet to rest for a minute, and store them in a warm oven."
      ]
    }
  ]
}

=== CJStandingwater/cookbook/recipes/8ae58438-9baa-4a8b-8786-e3fd59531e0a.json
{
  "id": "8ae58438-9baa-4a8b-8786-e3fd59531e0a",
  "title": "Apple Crinkle",
  "authors": [
    "Lynda Howard"
  ],
  "ingredients": [
    {
      "section": "Apple Mixture",
      "items": [
        {
          "ingredient": "Apple",
          "form": [
            "chopped"
          ],
          "volume_ml": 946.353,
          "note": "Finely"
        },
        {
          "ingredient": "Sugar",
          "volume_ml": 236.588
        },
        {
          "ingredient": "Flour",
          "volume_ml": 118.294
        },
        {
          "ingredient": "Brown Sugar",
          "volume_ml": 118.294
        }
      ]
    },
    {
      "section": "Topping",
      "items": [
        {
          "ingredient": "Oatmeal",
          "volume_ml": 118.294
        },
        {
          "ingredient": "Butter",
          "form": [
            "melted"
          ],
          "volume_ml": 118.294
        },
        {
          "ingredient": "Brown Sugar",
          "volume_ml": 59.147
        },
        {
          "ingredient": "Flour",
          "volume_ml": 29.574
        }
      ]
    }
  ],
  "instructions": [
    {
      "action": "preheat",
      "content": "Preheat oven to 350 degrees."
    },
    {
      "action": "mix",
      "content": "Mix Apples, Sugar, Flour, and Brown Sugar and pour into a buttered pan."
    },
    {
      "action": "mix",
      "content": "Mix Oatmeal, Melted Butter, Brown Sugar, and Flour and pour over apple mixture."
    },
    {
      "action": "bake",
      "content": "Bake for 45 minutes."
    }
  ],
  "timings": [
    {
      "title": "prep",
      "minutes": 10
    },
    {
      "title": "bake",
      "minutes": 45
    }
  ],
  "tags": [
    "dessert",
    "fall",
    "holiday",
    "comfort"
  ],
  "source": "Pantry Potpourri",
  "tools": [
    "Mixing Bowl",
    "Rubber Spatula",
    "Baking Dish"
  ],
  "difficulty": "easy"
}
